### ISSUE TITLE
Odd scrolling behaviour on iOS Safari

### ISSUE THREAD

**Issue by OliverCole** [mrvautin/githubdocs#1]
iOS Safari allows several scrolling related inputs, including:

1. Tap the very top of the screen to scroll to the top of the webpage
2. Continuous scrolling by placing another finger on screen before removing the previous one.

Neither of these work on the demo.

Let me know if you need a video or something.

**Comment by mrvautin** [comment]
Thanks for raising. I don't use Safari on iOS and had no idea these inputs even existed. They sound really handy!

I will have a look into it and see what I can find.

**Comment by mrvautin** [comment]
Fixed in latest version
